version: '3.7'

services:
  web:
    build: ./gardens_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gardens_app/:/usr/src/gardens_app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gardens
      - POSTGRES_PASSWORD=Js3tq2uWExRSpwEQ
      - POSTGRES_DB=gardens
      
volumes:
  postgres_data:
    
    